deploy_gitlab_runner:
  stage: infra
  extends:
  - .auto-configure
  - .before-script
  - .general
  variables:
  - $GITLAB_RUNNER_INSTALLED
  script:
  - helmfile -l component=gitlab-runner list
  - helm tiller run -- helmfile -l component=gitlab-runner sync --skip-deps