variables:
  HTTPBIN_HOSTNAME: $KUBE_INGRESS_BASE_DOMAIN

lint_helmfile:
  stage: lint
  extends:
  - .before-helmfile-script
  script:
  - helmfile list
  - helmfile deps
  - helmfile lint
  except:
    variables:
    - $HELMFILE_LINT_DISABLED == "yes"

.before-helmfile-script:
  before_script:
  - helmfile -v
