# This template can use to set up an AWS EKS cluster for specific project
# (group currently is not supported) and allows to you create and manage Nginx Ingress Controller,
# CertManager and other tools with custom values for Helm charts as you wish :)
#
variables:
  CI_IMAGE_NAME: $CI_REGISTRY_IMAGE:terraform-v${TERRAFORM_VERSION}-helmfile-${HELMFILE_VERSION}-doctl-${DOCTL_VERSION}-kubectl-${KUBECTL_VER}-helm-${HELM_VER}
  KUBECTL_VER: v1.16.0
  HELM_VER: v2.15.1
  HELMFILE_VERSION: v0.94.1 # https://github.com/roboll/helmfile/releases
  DOCTL_VERSION: 1.36.0 # https://github.com/digitalocean/doctl/releases
  TERRAFORM_VERSION: 0.12.18 # https://releases.hashicorp.com/terraform/
  #
  KUBEHOME_DIR: $CI_PROJECT_DIR/.kube
  KUBECONFIG: $CI_PROJECT_DIR/.kube/config
  # Terraform variables
  PLAN: plan.tfplan
  TF_VAR_kubeconfig_path: $CI_PROJECT_DIR/.kube/config
  TF_VAR_root_gitlab_project: $CI_PROJECT_ID
  # Set a group id to add a kubernetes cluster to its settings
  # ⚠️ REPLACE WITH YOUR OWN ⚠️
  TF_VAR_root_gitlab_group: 6638212
  TF_VAR_dns_zone: $KUBE_INGRESS_BASE_DOMAIN
  TF_VAR_gitlab_runner_installed: $GITLAB_RUNNER_INSTALLED
  # helmfiles
  # the helm charts are enabled for testing purposes, you may want to change these values to your own
  GITLAB_RUNNER_INSTALLED: "true"
  NGINX_INGRESS_INSTALLED: "true"
  CERT_MANAGER_INSTALLED: "true"
  # autoscaling is already configured by DOKS, you may want to install to AWS EKS
  # CLUSTER_AUTOSCALER_INSTALLED: "false"
  # helmfile environment variables
  CREATE_NAMESPACE_IF_MISSING: "true" # indicate whether the namespace should be created if it does not exist
  HELM_HOST: localhost:44134
  TILLER_NAMESPACE: tillerless

image:
  name: $CI_IMAGE_NAME
  entrypoint:
  - '/usr/bin/env'
  - 'PATH=/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin'

cache:
  paths:
  - .terraform

before_script:
- mkdir -p $KUBEHOME_DIR
- echo $KUBECONFIG
- terraform --version
- terraform init $TERRAFORM_DIR

stages:
- docker
- validate
- build
- test
- deploy
- gitlab
- infra
- destroy

validate:
  stage: validate
  extends:
  - .terraform
  script:
  - terraform validate $TERRAFORM_DIR

# !!! At the same time will be used EKS or DOKS only.
# Please, specify TERRAFORM_VARS and TERRAFORM_DIR environment variables
# according to your choice in the variables of top this file !!!
plan:
  stage: build
  extends: .terraform
  script:
  - terraform plan -var-file=$TERRAFORM_VARS -out=$PLAN $TERRAFORM_DIR
  artifacts:
    name: plan
    paths:
      - $PLAN

# !!! At the same time will be used EKS or DOKS only.
# Please, specify TERRAFORM_VARS and TERRAFORM_DIR environment variables
# according to your choice in the variables of top this file !!!
apply:
  stage: deploy
  extends: .terraform
  environment:
    name: production
  script:
  - terraform apply -input=false $PLAN
  dependencies:
  - plan
  when: manual
  allow_failure: false

destroy from web:
  extends: .destroy
  except:
  - schedules
  when: manual

destroy with delay:
  extends: .destroy
  only:
  - schedules
  when: delayed
  start_in: 5 minutes

.destroy:
  stage: destroy
  extends: .terraform
  environment:
    name: production
  script:
  - helm version -c
  - helm init -c
  - helm tiller install
  - helm tiller start-ci
  - ./scripts/destroy_helm_releases.sh
  - terraform destroy -var-file $TERRAFORM_VARS -auto-approve $TERRAFORM_DIR

# Builds the docker image, includes tools that might you want to use on the next stages
# Notice, that the $CI_IMAGE_NAME enviroment variables will be used in the next stage and 
# based on the some env variables
# The versions of terraform and helmfile are defined on top of gitlab ci file, you can set others values
# - TERRAFORM_VERSION
# - HELMFILE_VERSION
docker-build-master:
  # Official docker image.
  image: docker:latest
  stage: docker
  services:
  - docker:dind
  before_script:
  - docker login -u "$CI_REGISTRY_USER" -p "$CI_REGISTRY_PASSWORD" $CI_REGISTRY
  script:
  - docker build --pull -t "$CI_IMAGE_NAME" --build-arg terraform_ver=$TERRAFORM_VERSION --build-arg helm_ver=$HELM_VER --build-arg kubectl_ver=$KUBECTL_VER --build-arg helmfile_ver=$HELMFILE_VERSION --build-arg doctl_ver=$DOCTL_VERSION .
  - docker push "$CI_IMAGE_NAME"
  only:
    refs:
    - master
    - 1-add-support-for-doks-digital-ocean-kubernetes
    changes:
    - Dockerfile
    - helmfile.d/*

.auto-configure:
  image: $CI_IMAGE_NAME

.before-script:
  before_script:
  - apt-get install -yq procps
  - aws --version
  - doctl version
  - export KUBE_CLUSTER_NAME=${KUBE_CLUSTER_NAME:-$EKS_CLUSTER_NAME}
  - |
    if [[ $DOKS_CLUSTER_ENABLED == "yes" ]]; then
      doctl kubernetes cluster kubeconfig save $KUBE_CLUSTER_NAME
    elif [[ $AWS_EKS_CLUSTER_ENABLED == "yes" ]]; then
      aws eks update-kubeconfig --name $KUBE_CLUSTER_NAME
    fi
  - kubectl version
  - helm version -c
  - helm init -c
  - helm tiller install
  - helm tiller start-ci
  - helmfile -v
  - helmfile deps

# Heavily used by included gitlab templates
.general:
  only:
    refs:
    - master
    - 1-add-support-for-doks-digital-ocean-kubernetes
    variables:
    - $AWS_EKS_CLUSTER_ENABLED == "yes"
    - $DOKS_CLUSTER_ENABLED == "yes"
  dependencies:
  - apply
  tags:
  - docker

.aws_eks_cluster_enabled:
  only:
    variables:
    - $AWS_EKS_CLUSTER_ENABLED == "yes"

.doks_cluster_enabled:
  only:
    variables:
    - $DOKS_CLUSTER_ENABLED == "yes"

.terraform:
  extends: 
  - .aws_eks_cluster_enabled
  - .doks_cluster_enabled
  only:
    refs:
    - master
    - 1-add-support-for-doks-digital-ocean-kubernetes
  before_script:
  - mkdir -p $KUBEHOME_DIR
  - echo $KUBECONFIG
  - terraform --version
  - |
    if [[ $DOKS_CLUSTER_ENABLED == "yes" ]]; then
      export AWS_SECRET_ACCESS_KEY=$AWS_S3_BACKEND_SECRET_ACCESS_KEY
      export AWS_ACCESS_KEY_ID=$AWS_S3_BACKEND_ACCESS_KEY_ID
      export TERRAFORM_DIR=./terraform/doks
      export TERRAFORM_VARS=$TERRAFORM_DIR/fra1.tfvars
    elif [[ $AWS_EKS_CLUSTER_ENABLED == "yes" ]]; then
      export TERRAFORM_DIR="./terraform/aws-eks"
      export TERRAFORM_VARS="$TERRAFORM_DIR/eu-central-1.tfvars"
    fi
  - terraform init $TERRAFORM_DIR
  except:
    variables:
    - $TERRAFORM_DISABLED == "yes"

include:
- local: .gitlab/ci/templates/Jobs/Auto-Ingress.gitalb-ci.yml
- local: .gitlab/ci/templates/Jobs/Gitlab-Runner.gitlab-ci.yml
- local: .gitlab/ci/templates/Jobs/Cluster-AutoScaler.gitlab-ci.yml