repositories:
# Stable repo of official helm charts
- name: "lazyorange"
  url: "https://gitlab.com/lazyorangejs/staging.lazyorange.xyz/-/raw/98a54fbd36383e7a2177bff8fbe2b4607e7efefc/charts/index"

releases:
#
# References:
#   - https://gitlab.com/lazyorangejs/staging.lazyorange.xyz/-/merge_requests/9
#
- name: "httpbin"
  namespace: "testing"
  labels:
    chart: "httpbin"
    repo: "lazyorange"
    component: "testing"
    namespace: "testing"
    default: "false"
  chart: "lazyorange/httpbin"
  version: "0.1.0"
  wait: true
  installed: {{ env "HTTPBIN_INSTALLED" | default "false" }}
  values:
    - ingress:
        enabled: true
        hosts:
        - host: {{ requiredEnv "HTTPBIN_HOSTNAME" }}
          paths: [ '/' ]
        tls:
        - secretName: httpbin-tls
          hosts:
          - {{ requiredEnv "HTTPBIN_HOSTNAME" }}